import { Product } from "@/types/product";

// Local fixture data — used automatically whenever Shopify isn't configured
// (see lib/catalog.ts). Shaped as closely as possible to what the Shopify
// adapter returns, so switching over is a data-source change, not a UI change.
// shopify_variant_id is null here because these aren't real Shopify variants —
// once Shopify is connected, cart/checkout automatically uses live variant IDs.

const base = {
  shopify_variant_id: null,
  images: [],
  before_after_images: [],
  status: "live" as const,
};

export const products: Product[] = [
  // ---- Fullmoon (dry/dull skin) ----
  {
    ...base,
    id: "1",
    slug: "fullmoon-face-wash",
    name: "Fullmoon Face Wash",
    tagline: "Brightening face wash for dull, uneven-looking skin",
    description:
      "A brightening cleanser designed to wash away daily impurities and help improve the look of dull, uneven skin tone. Aloe Vera Extract helps keep the cleansing experience feeling soothing and comfortable.",
    key_benefits: ["Helps skin look brighter and fresher", "Helps improve the appearance of uneven skin tone", "Cleanses while supporting a comfortable skin feel"],
    key_ingredients: [
      { name: "Seaweed", explanation: "Helps condition skin and support a fresh-looking complexion." },
      { name: "Glycolic Acid", explanation: "An exfoliating AHA that helps smooth the look of rough texture and dullness." },
      { name: "Aloe Vera Extract", explanation: "Helps soothe and hydrate the skin." },
      { name: "Niacinamide", explanation: "Helps improve the look of uneven tone and supports the skin barrier." },
    ],
    full_ingredient_list: "Seaweed, Glycolic Acid, Aloe Vera Extract, Niacinamide.",
    skin_hair_type: ["Dull Skin", "Uneven Skin Tone"],
    how_to_use: "Massage onto damp skin morning and night, rinse thoroughly.",
    category: "skincare",
    subrange: "Fullmoon",
    concern_tags: ["Dry Skin"],
    routine_tags: ["Morning", "Night"],
    price_inr: 199,
    compare_at_price_inr: 349,
    stock_quantity: 40,
    sku: "HL-SKC-FMW-100",
    is_bestseller: false,
    is_featured: true,
    is_new: false,
    rating: 4.5,
    review_count: 214,
  },
  {
    ...base,
    id: "2",
    slug: "fullmoon-face-serum",
    name: "Fullmoon Face Serum",
    tagline: "Whitening and brightening serum for uneven-looking skin tone",
    description:
      "A targeted skin-brightening serum formulated with 1% Kojic Acid, 1% Hyaluronic Acid and 1% Pro-Vitamin B5. Designed to help reduce the appearance of dark spots and uneven tone while hydrating skin for a smoother, more radiant-looking complexion.",
    key_benefits: ["Helps improve the appearance of dark spots and uneven skin tone", "Supports a brighter, more even-looking complexion", "Hydrates skin and helps maintain a soft, comfortable feel"],
    key_ingredients: [
      { name: "Kojic Acid 1%", explanation: "Helps reduce the appearance of dark spots and uneven pigmentation for a brighter-looking complexion." },
      { name: "Hyaluronic Acid 1%", explanation: "Helps attract and retain moisture so skin looks plump and hydrated." },
      { name: "Pro-Vitamin B5 1% (Panthenol)", explanation: "Helps soothe skin and support moisture retention." },
    ],
    full_ingredient_list: "1% Kojic Acid, 1% Hyaluronic Acid, 1% Pro-Vitamin B5.",
    skin_hair_type: ["Uneven Skin Tone", "Dull Skin"],
    how_to_use: "Apply a few drops to face and neck as the last step of your night routine.",
    category: "skincare",
    subrange: "Fullmoon",
    concern_tags: ["Dry Skin"],
    routine_tags: ["Night"],
    price_inr: 325,
    compare_at_price_inr: 599,
    stock_quantity: 30,
    sku: "HL-SKC-FMS-30",
    is_bestseller: false,
    is_featured: true,
    is_new: false,
    rating: 4.7,
    review_count: 528,
  },
  // ---- Blemish Block (acne) ----
  {
    ...base,
    id: "3",
    slug: "blemish-block-face-wash",
    name: "Blemish Block Face Wash",
    tagline: "Anti-acne face wash for blemish-prone skin",
    description:
      "A daily cleansing face wash formulated with Tea Tree, Piroctone, Seaweed and Betaine. Designed to cleanse away daily impurities and excess oil while helping keep blemish-prone skin feeling fresh and comfortable.",
    key_benefits: ["Cleanses away daily impurities and excess oil", "Helps keep blemish-prone skin feeling fresh", "Cleanses without leaving skin feeling overly dry"],
    key_ingredients: [
      { name: "Tea Tree", explanation: "Helps care for blemish-prone skin and excess oil." },
      { name: "Piroctone", explanation: "Helps maintain a clean-feeling complexion." },
      { name: "Seaweed", explanation: "Helps condition skin and support a fresh-looking feel." },
      { name: "Betaine", explanation: "Helps maintain moisture and skin comfort during cleansing." },
    ],
    full_ingredient_list: "Tea Tree, Piroctone, Seaweed, Betaine.",
    skin_hair_type: ["Oily Skin", "Acne-Prone Skin"],
    how_to_use: "Massage onto damp skin morning and night, rinse thoroughly.",
    category: "skincare",
    subrange: "Blemish Block",
    concern_tags: ["Acne", "Oily Skin"],
    routine_tags: ["Morning", "Night"],
    price_inr: 199,
    compare_at_price_inr: 349,
    stock_quantity: 55,
    sku: "HL-SKC-BBW-100",
    is_bestseller: true,
    is_featured: true,
    is_new: false,
    rating: 4.4,
    review_count: 356,
  },
  {
    ...base,
    id: "4",
    slug: "blemish-block-face-serum",
    name: "Blemish Block Face Serum",
    tagline: "Anti-acne serum for blemish-prone skin",
    description:
      "A targeted anti-acne serum formulated with 0.5% Salicylic Acid, 0.5% Succinic Acid, 5% Niacinamide and 2% Allantoin. Designed to help unclog pores, reduce the appearance of blemishes and excess oil, and support calmer-looking skin.",
    key_benefits: ["Helps reduce the appearance of acne and blemishes", "Helps manage excess oil and the look of congested pores", "Helps soothe skin and improve the appearance of post-blemish marks"],
    key_ingredients: [
      { name: "Salicylic Acid 0.5%", explanation: "Helps exfoliate inside pores and reduce the look of congestion." },
      { name: "Succinic Acid 0.5%", explanation: "Helps support blemish-prone skin and improve the look of imperfections." },
      { name: "Niacinamide 5%", explanation: "Helps balance the appearance of oiliness and improve uneven-looking tone." },
      { name: "Allantoin 2%", explanation: "Helps soothe and condition skin for a more comfortable feel." },
    ],
    full_ingredient_list: "0.5% Salicylic Acid, 0.5% Succinic Acid, 5% Niacinamide, 2% Allantoin.",
    skin_hair_type: ["Oily Skin", "Acne-Prone Skin", "Combination Skin"],
    how_to_use: "Apply a thin layer to clean skin, morning and night, before moisturiser.",
    category: "skincare",
    subrange: "Blemish Block",
    concern_tags: ["Acne", "Oily Skin"],
    routine_tags: ["Morning", "Night"],
    price_inr: 325,
    compare_at_price_inr: 599,
    stock_quantity: 58,
    sku: "HL-SKC-BBS-30",
    is_bestseller: true,
    is_featured: true,
    is_new: false,
    rating: 4.8,
    review_count: 812,
  },
  // ---- Velvet Touch (everyday skincare) ----
  {
    ...base,
    id: "5",
    slug: "velvet-touch-face-wash",
    name: "Velvet Touch Face Wash",
    tagline: "Soft creamy-foam face wash for soft, smooth skin",
    description:
      "A soap-based face wash that creates a soft, creamy foam to cleanse daily impurities and excess oil. Formulated with Coconut Milk, Liquorice, Aloe Vera Extract, Niacinamide, Pro-Vitamin B5, Fatty Acids and Betaine to help soften and smooth the feel of skin while supporting a fresh, balanced-looking complexion.",
    key_benefits: ["Soft, creamy foam for an enjoyable cleansing experience", "Helps leave skin feeling soft, smooth and refreshed", "Helps remove excess oil while maintaining skin comfort"],
    key_ingredients: [
      { name: "Coconut Milk", explanation: "Helps condition skin for a soft, nourished feel." },
      { name: "Liquorice", explanation: "Helps improve the appearance of uneven-looking skin tone." },
      { name: "Aloe Vera Extract", explanation: "Helps soothe and hydrate skin." },
      { name: "Niacinamide", explanation: "Helps support the skin barrier and balance the look of oiliness." },
      { name: "Pro-Vitamin B5", explanation: "Helps maintain moisture and skin comfort." },
      { name: "Fatty Acids", explanation: "Help condition skin and support a smooth-feeling finish." },
      { name: "Betaine", explanation: "Helps maintain hydration and comfort during cleansing." },
    ],
    full_ingredient_list: "Coconut Milk, Liquorice, Aloe Vera Extract, Niacinamide, Pro-Vitamin B5, Fatty Acids, Betaine.",
    skin_hair_type: ["All Skin Types", "Oily Skin"],
    how_to_use: "Massage onto damp skin morning and night, rinse thoroughly.",
    category: "skincare",
    subrange: "Velvet Touch",
    concern_tags: [],
    routine_tags: ["Morning", "Night"],
    price_inr: 199,
    compare_at_price_inr: 349,
    stock_quantity: 60,
    sku: "HL-SKC-VTW-100",
    is_bestseller: false,
    is_featured: false,
    is_new: false,
    rating: 4.5,
    review_count: 189,
  },
  {
    ...base,
    id: "6",
    slug: "velvet-touch-face-serum",
    name: "Velvet Touch Face Serum",
    tagline: "Weekly AHA, BHA & PHA exfoliating serum for smoother, brighter-looking skin",
    description:
      "An exfoliating AHA, BHA and PHA serum formulated with 2% Glycolic Acid, 5% Lactic Acid, 2% Citric Acid, 1% Salicylic Acid and Gluconolactone. Use 2–3 times per week at night to help exfoliate dead surface skin cells, smooth rough texture and improve the appearance of uneven tone and dullness. Daily sunscreen is essential while using exfoliating acids: use Humor Luxury Light & Shade Sunscreen SPF 50 or another broad-spectrum SPF 30+ sunscreen every morning, and reapply as directed.",
    key_benefits: ["Helps exfoliate dead surface skin cells and smooth rough texture", "Helps improve the appearance of uneven tone, pigmentation and dullness", "Use 2–3 nights weekly and pair with daily broad-spectrum sunscreen"],
    key_ingredients: [
      { name: "Glycolic Acid 2% (AHA)", explanation: "Helps exfoliate the skin surface and smooth the look of rough texture." },
      { name: "Lactic Acid 5% (AHA)", explanation: "Helps exfoliate and support a smoother, brighter-looking complexion." },
      { name: "Citric Acid 2% (AHA)", explanation: "Helps exfoliate the surface and improve the look of dullness." },
      { name: "Salicylic Acid 1% (BHA)", explanation: "Helps clear pore buildup and smooth the look of congested skin." },
      { name: "Gluconolactone (PHA)", explanation: "A gentle exfoliating polyhydroxy acid that helps refine skin texture." },
    ],
    full_ingredient_list: "2% Glycolic Acid, 5% Lactic Acid, 2% Citric Acid, 1% Salicylic Acid, Gluconolactone.",
    skin_hair_type: ["Uneven Skin Tone", "Dull Skin", "Textured Skin"],
    how_to_use: "Use 2–3 nights per week. Apply 3–4 drops to clean, dry skin at night and follow with moisturiser. Every morning, apply a broad-spectrum SPF 30+ sunscreen and reapply as directed.",
    category: "skincare",
    subrange: "Velvet Touch",
    concern_tags: ["Pigmentation"],
    routine_tags: ["Morning"],
    price_inr: 325,
    compare_at_price_inr: 599,
    stock_quantity: 42,
    sku: "HL-SKC-VTS-30",
    is_bestseller: true,
    is_featured: true,
    is_new: false,
    rating: 4.6,
    review_count: 812,
  },
  // ---- Sun Care ----
  {
    ...base,
    id: "7",
    slug: "sunscreen-spf-50",
    name: "Light & Shade Sunscreen SPF 50",
    tagline: "Lightweight daily sun protection",
    description:
      "A broad-spectrum SPF 50 sunscreen with a no-white-cast finish, light enough to wear every day under makeup.",
    key_benefits: ["Broad-spectrum UVA/UVB protection", "No white cast, blends into all skin tones", "Non-greasy, matte-leaning finish"],
    key_ingredients: [{ name: "Broad-spectrum UV filters", explanation: "Protects against UVA and UVB exposure." }],
    full_ingredient_list: "Aqua, Homosalate, Octocrylene, Avobenzone, Niacinamide, Dimethicone, Phenoxyethanol.",
    skin_hair_type: ["All Skin Types"],
    how_to_use: "Apply generously as the last step of your morning routine. Reapply every 3–4 hours in direct sun.",
    category: "skincare",
    subrange: null,
    concern_tags: ["Sun Protection"],
    routine_tags: ["Morning"],
    price_inr: 299,
    compare_at_price_inr: 549,
    stock_quantity: 70,
    sku: "HL-SKC-SUN-50",
    is_bestseller: true,
    is_featured: true,
    is_new: true,
    rating: 4.7,
    review_count: 342,
  },
  // ---- Hair Care ----
  {
    ...base,
    id: "8",
    slug: "repair-shampoo",
    name: "Protein Shake Anti Hairfall Shampoo",
    tagline: "Anti-hair fall shampoo with plant and protein care",
    description:
      "A daily shampoo formulated with Aloe Vera, Oat, Corn, Algae, Silk Protein, Pea Protein and Soybean. Designed to cleanse the scalp and hair while helping reduce the appearance of hair fall due to breakage and leaving hair feeling softer and stronger.",
    key_benefits: ["Helps reduce hair fall caused by breakage", "Gently cleanses the scalp and hair", "Helps leave hair feeling smoother, softer and stronger"],
    key_ingredients: [
      { name: "Aloe Vera", explanation: "Helps condition the scalp and maintain moisture." },
      { name: "Oat", explanation: "Helps soothe and condition the scalp and hair." },
      { name: "Corn", explanation: "Provides plant-derived conditioning support for hair." },
      { name: "Algae", explanation: "Helps condition hair and support a healthy-looking finish." },
      { name: "Silk Protein", explanation: "Helps smooth the hair surface and improve softness." },
      { name: "Pea Protein", explanation: "Helps strengthen the feel of hair and improve manageability." },
      { name: "Soybean", explanation: "Provides plant-derived protein and conditioning support." },
    ],
    full_ingredient_list: "Aloe Vera, Oat, Corn, Algae, Silk Protein, Pea Protein, Soybean.",
    skin_hair_type: ["Weak Hair", "Breakage-Prone Hair", "Dry Hair"],
    how_to_use: "Apply to wet hair, massage into scalp and lengths, rinse. Follow with conditioner.",
    category: "haircare",
    subrange: null,
    concern_tags: ["Hair Care"],
    routine_tags: ["Hair Care Routine"],
    price_inr: 375,
    compare_at_price_inr: 699,
    stock_quantity: 65,
    sku: "HL-HRC-SHM-250",
    is_bestseller: true,
    is_featured: true,
    is_new: false,
    rating: 4.5,
    review_count: 291,
  },
  {
    ...base,
    id: "9",
    slug: "repair-conditioner",
    name: "Silk Shake Smooth Shine Conditioner",
    tagline: "Silky-smooth shine and easy detangling for everyday hair care",
    description:
      "A smoothing conditioner formulated with Keratin, Sodium Hyaluronate, Glycerin, Bee Pollen and Betaine. It helps detangle lengths, soften rough-feeling strands and tame the look of frizz, leaving hair smoother, shinier and easier to manage without a heavy finish.",
    key_benefits: ["Helps detangle hair and improve manageability", "Leaves hair feeling soft and looking silky-smooth", "Helps tame frizz and enhance the appearance of shine"],
    key_ingredients: [
      { name: "Keratin", explanation: "Helps smooth the feel of damaged, rough hair and improve manageability." },
      { name: "Sodium Hyaluronate", explanation: "Helps attract and retain moisture for softer-feeling hair." },
      { name: "Glycerin", explanation: "Helps draw in moisture and reduce the feel of dryness." },
      { name: "Bee Pollen", explanation: "Provides conditioning support for a nourished-feeling finish." },
      { name: "Betaine", explanation: "Helps condition hair and improve softness and combability." },
    ],
    full_ingredient_list: "Keratin, Sodium Hyaluronate, Glycerin, Bee Pollen, Betaine.",
    skin_hair_type: ["Dry Hair", "Frizzy Hair", "Tangled Hair"],
    how_to_use: "Apply from mid-length to ends after shampooing, leave 2–3 minutes, rinse.",
    category: "haircare",
    subrange: null,
    concern_tags: ["Smoothing", "Shine", "Detangling", "Frizz Control"],
    routine_tags: ["Hair Care Routine"],
    price_inr: 249,
    compare_at_price_inr: 449,
    stock_quantity: 50,
    sku: "HL-HRC-CND-250",
    is_bestseller: false,
    is_featured: false,
    is_new: false,
    rating: 4.4,
    review_count: 133,
  },
  {
    ...base,
    id: "10",
    slug: "repair-hair-mask",
    name: "Milk Shake Repairing Smooth Hair Mask",
    tagline: "Premium deep-conditioning mask for silky, smooth, bouncy hair",
    description:
      "A premium intensive hair mask formulated with Keratin, Sodium Hyaluronate, Glycerin, Bee Pollen and Betaine. Created for dry, dull or damage-prone lengths, this rich treatment helps deeply condition hair, improve the feel of roughness, reduce the appearance of frizz and leave strands silky-smooth, glossy and full of bounce.",
    key_benefits: ["Intensive conditioning for dry and damage-prone lengths", "Helps hair feel silky-smooth, soft and more elastic", "Helps control the appearance of frizz and improve shine", "Leaves hair feeling bouncy, nourished and easier to style"],
    key_ingredients: [
      { name: "Keratin", explanation: "Helps smooth the feel of damaged hair and improve the look of strength and manageability." },
      { name: "Sodium Hyaluronate", explanation: "Helps attract and retain moisture so hair feels softer and less dry." },
      { name: "Glycerin", explanation: "Helps draw in moisture to support a supple, conditioned feel." },
      { name: "Bee Pollen", explanation: "Provides conditioning support as part of the mask's premium care blend." },
      { name: "Betaine", explanation: "Helps soften hair and improve slip for easier detangling." },
    ],
    full_ingredient_list: "Keratin, Sodium Hyaluronate, Glycerin, Bee Pollen, Betaine.",
    skin_hair_type: ["Dry Hair", "Damaged Hair", "Frizzy Hair", "Dull Hair"],
    how_to_use: "Apply generously after shampooing, leave 10–15 minutes, rinse thoroughly. Use 1–2 times weekly.",
    category: "haircare",
    subrange: null,
    concern_tags: ["Deep Conditioning", "Damage Care", "Smoothness", "Bounce", "Shine"],
    routine_tags: ["Hair Care Routine"],
    price_inr: 475,
    compare_at_price_inr: 899,
    stock_quantity: 35,
    sku: "HL-HRC-MSK-200",
    is_bestseller: false,
    is_featured: false,
    is_new: true,
    rating: 4.6,
    review_count: 87,
  },
  // ---- Body Care ----
  {
    ...base,
    id: "11",
    slug: "shower-gel",
    name: "Royal Water Soft Shower Cream",
    tagline: "Everyday gentle body wash",
    description:
      "A gentle, sulphate-free body wash that cleanses without drying out skin, for daily use across the whole body.",
    key_benefits: ["Cleanses without over-drying", "Light, non-lingering fragrance", "Suitable for daily use"],
    key_ingredients: [{ name: "Glycerin", explanation: "Keeps the cleanse comfortable, not stripping." }],
    full_ingredient_list: "Aqua, Sodium Cocoyl Isethionate, Glycerin, Cocamidopropyl Betaine, Citric Acid, Phenoxyethanol, Parfum.",
    skin_hair_type: ["All Skin Types"],
    how_to_use: "Massage onto wet skin, lather, rinse thoroughly.",
    category: "bodycare",
    subrange: null,
    concern_tags: [],
    routine_tags: [],
    price_inr: 225,
    compare_at_price_inr: 399,
    stock_quantity: 80,
    sku: "HL-BDC-SHG-300",
    is_bestseller: false,
    is_featured: false,
    is_new: false,
    rating: 4.3,
    review_count: 96,
  },
];

export function getProducts() {
  return products.filter((p) => p.status === "live");
}

export function getFeaturedProducts() {
  return products.filter((p) => p.is_featured && p.status === "live");
}

export function getProductBySlug(slug: string) {
  return products.find((p) => p.slug === slug && p.status === "live");
}

export function getProductsByConcern(concern: string) {
  return products.filter((p) => p.concern_tags.includes(concern) && p.status === "live");
}

export function getProductsBySubrange(subrange: string) {
  return products.filter((p) => p.subrange === subrange && p.status === "live");
}

export function getProductsByCategory(category: Product["category"]) {
  return products.filter((p) => p.category === category && p.status === "live");
}
