"use client";

import { useEffect, useState } from "react";

type Application={userId:string;email?:string;phone?:string;application:{businessName:string;gstPan:string;address:string;mobile:string;photoNames:string[];appliedAt:string}};
export default function AdminMarketingPartners(){
 const [apps,setApps]=useState<Application[]>([]);const [loggedIn,setLoggedIn]=useState(true);const [loading,setLoading]=useState(true);const [saving,setSaving]=useState("");const [error,setError]=useState("");
 async function load(){setLoading(true);const r=await fetch("/api/admin/marketing-partners",{cache:"no-store"});if(r.status===401){setLoggedIn(false);setLoading(false);return;}const d=await r.json();if(!r.ok){setError(d.error||"Could not load.");}else setApps(d.applications||[]);setLoading(false);}
 useEffect(()=>{load();},[]);
 async function act(userId:string,action:"approve"|"reject"){setSaving(userId);setError("");const r=await fetch("/api/admin/marketing-partners",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({userId,action})});const d=await r.json();if(!r.ok)setError(d.error||"Could not update.");else setApps(a=>a.filter(x=>x.userId!==userId));setSaving("");}
 if(!loggedIn)return <main className="max-w-xl mx-auto px-5 py-24 text-center"><h1 className="font-display text-3xl text-[var(--deep-wine)]">Admin Login Required</h1><p className="text-sm text-[var(--muted)] mt-2">Open the main admin panel first and sign in.</p></main>;
 return <main className="min-h-[70vh] bg-[var(--milk-sage)] px-5 md:px-8 py-10"><div className="max-w-6xl mx-auto"><div className="flex items-end justify-between gap-4 mb-7"><div><p className="text-xs uppercase tracking-[0.2em] text-[var(--warm-gold)]">Humor Luxury</p><h1 className="font-display text-3xl md:text-4xl text-[var(--deep-wine)] mt-2">Marketing Partner Applications</h1></div><button onClick={load} className="rounded-full bg-white border border-[var(--line)] px-5 py-2.5 text-xs">Refresh</button></div>{error&&<p className="mb-5 rounded-xl bg-red-50 px-4 py-3 text-sm text-red-700">{error}</p>}{loading?<p className="text-sm text-[var(--muted)]">Loading…</p>:apps.length===0?<div className="rounded-3xl bg-white border border-[var(--line)] p-8 text-sm text-[var(--muted)]">No pending applications.</div>:<div className="space-y-5">{apps.map(app=><div key={app.userId} className="rounded-3xl bg-white border border-[var(--line)] p-6"><div className="grid md:grid-cols-2 gap-5"><div><p className="text-xs text-[var(--muted)]">Business</p><h2 className="font-display text-2xl text-[var(--deep-wine)] mt-1">{app.application.businessName}</h2><p className="text-sm mt-3"><strong>GST / PAN:</strong> {app.application.gstPan}</p><p className="text-sm mt-1"><strong>Mobile:</strong> {app.application.mobile}</p><p className="text-sm mt-1"><strong>Account:</strong> {app.email||app.phone||"—"}</p></div><div><p className="text-xs text-[var(--muted)]">Business address</p><p className="text-sm leading-6 mt-1">{app.application.address}</p><p className="text-xs text-[var(--muted)] mt-4">Photos selected: {app.application.photoNames?.join(", ")}</p></div></div><div className="mt-6 flex flex-col sm:flex-row gap-3"><button disabled={!!saving} onClick={()=>act(app.userId,"approve")} className="rounded-full bg-[var(--deep-wine)] text-white px-6 py-3 text-sm disabled:opacity-50">{saving===app.userId?"Processing…":"Approve & Generate Code"}</button><button disabled={!!saving} onClick={()=>act(app.userId,"reject")} className="rounded-full border border-red-200 text-red-700 px-6 py-3 text-sm disabled:opacity-50">Reject</button></div></div>)}</div>}</div></main>;
}
