-- Humor Luxury product seed
-- Run this ONCE in Supabase SQL Editor after the existing schema.
-- The website cart uses catalog IDs 1-11, while Supabase products.id is UUID.
-- catalog_id keeps that frontend mapping stable.

alter table products add column if not exists catalog_id integer;
create unique index if not exists idx_products_catalog_id on products(catalog_id);

insert into products (
  catalog_id, slug, name, tagline, description, key_benefits, key_ingredients,
  full_ingredient_list, skin_hair_type, how_to_use, category, concern_tags,
  routine_tags, price_inr, compare_at_price_inr, stock_quantity, sku,
  images, before_after_images, is_bestseller, is_featured, status
)
values
(1, 'fullmoon-face-wash', 'Fullmoon Face Wash', 'Gentle cleanser for dry, dull skin', 'A cream-based cleanser that removes impurities without stripping the skin, formulated for dry and dull complexions that need cleansing without tightness afterward.', ARRAY['Cleanses without stripping natural moisture','Softens rough, dull texture','Leaves skin comfortable, never tight'], '[{"name":"Glycerin","explanation":"Draws moisture into the skin during cleansing."},{"name":"Oat Extract","explanation":"Soothes and calms while cleansing."}]'::jsonb, 'Aqua, Glycerin, Cocamidopropyl Betaine, Avena Sativa (Oat) Kernel Extract, Panthenol, Citric Acid, Phenoxyethanol.', ARRAY['Dry Skin','Dull Skin'], 'Massage onto damp skin morning and night, rinse thoroughly.', 'skincare', ARRAY['Dry Skin'], ARRAY['Morning','Night'], 199, 349, 40, 'HL-SKC-FMW-100', ARRAY[]::text[], '[]'::jsonb, false, true, 'live'),
(2, 'fullmoon-face-serum', 'Fullmoon Face Serum', 'Overnight recovery serum for dry, dull skin', 'A deeply nourishing serum built to lock in moisture and support the skin barrier, for skin that wakes up feeling replenished rather than tight.', ARRAY['Restores moisture lost through the day','Supports a stronger-feeling skin barrier','Softer, more comfortable skin by morning'], '[{"name":"Ceramide Complex","explanation":"Helps rebuild the skin''s natural moisture barrier."},{"name":"Squalane","explanation":"A lightweight oil that mimics skin''s own lipids."}]'::jsonb, 'Aqua, Squalane, Glycerin, Ceramide NP, Panthenol, Phenoxyethanol, Tocopherol.', ARRAY['Dry Skin','Sensitive Skin'], 'Apply a few drops to face and neck as the last step of your night routine.', 'skincare', ARRAY['Dry Skin'], ARRAY['Night'], 325, 599, 30, 'HL-SKC-FMS-30', ARRAY[]::text[], '[]'::jsonb, false, true, 'live'),
(3, 'blemish-block-face-wash', 'Blemish Block Face Wash', 'Oil-control cleanser for acne-prone skin', 'A gel cleanser with salicylic acid and niacinamide that clears congestion and controls shine without over-drying acne-prone skin.', ARRAY['Reduces the look of breakouts','Controls excess oil through the day','Non-drying, safe for daily use'], '[{"name":"Salicylic Acid (0.5%)","explanation":"Gently clears congestion within pores."},{"name":"Niacinamide","explanation":"Regulates oil and calms the look of irritation."}]'::jsonb, 'Aqua, Salicylic Acid, Niacinamide, Cocamidopropyl Betaine, Glycerin, Phenoxyethanol.', ARRAY['Oily Skin','Acne-Prone'], 'Massage onto damp skin morning and night, rinse thoroughly.', 'skincare', ARRAY['Acne','Oily Skin'], ARRAY['Morning','Night'], 199, 349, 55, 'HL-SKC-BBW-100', ARRAY[]::text[], '[]'::jsonb, true, true, 'live'),
(4, 'blemish-block-face-serum', 'Blemish Block Face Serum', 'Niacinamide gel-serum for acne-prone skin', 'A featherweight gel-serum that pairs niacinamide with zinc PCA to calm the look of breakouts and manage excess shine, without the tight, over-dried feeling many acne products leave behind.', ARRAY['Reduces the appearance of shine through the day','Calms the look of active breakouts and redness','Non-comedogenic — won''t clog pores'], '[{"name":"Niacinamide 5%","explanation":"Regulates oil production and visibly refines the look of pores."},{"name":"Zinc PCA","explanation":"Helps control shine and supports a calmer-looking complexion."}]'::jsonb, 'Aqua, Niacinamide, Zinc PCA, Salicylic Acid, Glycerin, Propanediol, Carbomer, Phenoxyethanol.', ARRAY['Oily Skin','Acne-Prone','Combination'], 'Apply a thin layer to clean skin, morning and night, before moisturiser.', 'skincare', ARRAY['Acne','Oily Skin'], ARRAY['Morning','Night'], 325, 599, 58, 'HL-SKC-BBS-30', ARRAY[]::text[], '[]'::jsonb, true, true, 'live'),
(5, 'velvet-touch-face-wash', 'Velvet Touch Face Wash', 'Everyday gentle cleanser, all skin types', 'A mild, low-lather daily cleanser suited to any skin type — the reliable first step for anyone building a simple, everyday routine.', ARRAY['Cleanses gently without disrupting the skin barrier','Suitable for daily, twice-a-day use','Fragrance-light formula'], '[{"name":"Glycerin","explanation":"Keeps the cleanse from feeling stripping."},{"name":"Panthenol","explanation":"Supports visible skin comfort."}]'::jsonb, 'Aqua, Glycerin, Cocamidopropyl Betaine, Panthenol, Citric Acid, Phenoxyethanol.', ARRAY['All Skin Types'], 'Massage onto damp skin morning and night, rinse thoroughly.', 'skincare', ARRAY[]::text[], ARRAY['Morning','Night'], 199, 349, 60, 'HL-SKC-VTW-100', ARRAY[]::text[], '[]'::jsonb, false, false, 'live'),
(6, 'velvet-touch-face-serum', 'Velvet Touch Face Serum', 'Brightening vitamin C serum for everyday tone', 'A lightweight, fast-absorbing serum built around stabilised Vitamin C to visibly brighten skin and soften the look of dark spots over time.', ARRAY['Visibly brightens dull, uneven skin tone','Softens the look of dark spots and pigmentation','Lightweight — layers well under moisturiser'], '[{"name":"Vitamin C (Sodium Ascorbyl Phosphate)","explanation":"A stable form of Vitamin C that brightens without irritation."},{"name":"Hyaluronic Acid","explanation":"Draws in moisture so the serum feels hydrating, not stripping."}]'::jsonb, 'Aqua, Sodium Ascorbyl Phosphate, Niacinamide, Glycerin, Sodium Hyaluronate, Phenoxyethanol, Tocopherol.', ARRAY['All Skin Types','Uneven Tone'], 'Apply 3–4 drops every morning before moisturiser and SPF.', 'skincare', ARRAY['Pigmentation'], ARRAY['Morning'], 325, 599, 42, 'HL-SKC-VTS-30', ARRAY[]::text[], '[]'::jsonb, true, true, 'live'),
(7, 'sunscreen-spf-50', 'Sunscreen SPF 50 PA++++', 'Lightweight daily sun protection', 'A broad-spectrum SPF 50 sunscreen with a no-white-cast finish, light enough to wear every day under makeup.', ARRAY['Broad-spectrum UVA/UVB protection','No white cast, blends into all skin tones','Non-greasy, matte-leaning finish'], '[{"name":"Broad-spectrum UV filters","explanation":"Protects against UVA and UVB exposure."}]'::jsonb, 'Aqua, Homosalate, Octocrylene, Avobenzone, Niacinamide, Dimethicone, Phenoxyethanol.', ARRAY['All Skin Types'], 'Apply generously as the last step of your morning routine. Reapply every 3–4 hours in direct sun.', 'skincare', ARRAY['Sun Protection'], ARRAY['Morning'], 299, 549, 70, 'HL-SKC-SUN-50', ARRAY[]::text[], '[]'::jsonb, true, true, 'live'),
(8, 'repair-shampoo', 'Repair Shampoo', 'Sulphate-free shampoo for damaged, frizzy hair', 'A sulphate-free, protein-enriched shampoo that cleanses without stripping. Built for hair that''s colour-treated, heat-styled, or just needs a little extra softness back.', ARRAY['Cleanses gently without stripping natural oils','Reduces the look of frizz and flyaways','Safe for colour-treated hair'], '[{"name":"Hydrolysed Milk Protein","explanation":"Helps strengthen and smooth the hair shaft."},{"name":"Argan Oil","explanation":"Adds shine and softness without weighing hair down."}]'::jsonb, 'Aqua, Sodium Cocoyl Isethionate, Cocamidopropyl Betaine, Hydrolysed Milk Protein, Argania Spinosa Oil, Glycerin, Phenoxyethanol.', ARRAY['Dry Hair','Frizzy Hair','Colour-Treated Hair'], 'Apply to wet hair, massage into scalp and lengths, rinse. Follow with conditioner.', 'haircare', ARRAY['Hair Care'], ARRAY['Hair Care Routine'], 375, 699, 65, 'HL-HRC-SHM-250', ARRAY[]::text[], '[]'::jsonb, true, true, 'live'),
(9, 'repair-conditioner', 'Repair Conditioner', 'Detangling conditioner for damaged, frizzy hair', 'A rich conditioner that detangles and smooths without weighing hair down — the second half of the Repair duo.', ARRAY['Detangles without heaviness','Smooths flyaways and frizz','Softer, more manageable hair'], '[{"name":"Hydrolysed Milk Protein","explanation":"Continues the strengthening effect from the shampoo."},{"name":"Shea Butter","explanation":"Softens and smooths the hair surface."}]'::jsonb, 'Aqua, Cetearyl Alcohol, Behentrimonium Chloride, Hydrolysed Milk Protein, Butyrospermum Parkii (Shea) Butter, Phenoxyethanol.', ARRAY['Dry Hair','Frizzy Hair'], 'Apply from mid-length to ends after shampooing, leave 2–3 minutes, rinse.', 'haircare', ARRAY['Hair Care'], ARRAY['Hair Care Routine'], 249, 449, 50, 'HL-HRC-CND-250', ARRAY[]::text[], '[]'::jsonb, false, false, 'live'),
(10, 'repair-hair-mask', 'Repair Hair Mask', 'Weekly deep-repair treatment mask', 'An intensive weekly treatment for chemically-treated or heat-damaged hair — a deeper dose of the same repair actives as the shampoo and conditioner.', ARRAY['Deep conditioning for very dry or damaged hair','Reduces breakage over consistent use','Leaves hair visibly smoother'], '[{"name":"Hydrolysed Milk Protein","explanation":"Concentrated strengthening treatment."},{"name":"Argan Oil","explanation":"Deep nourishment for very dry lengths and ends."}]'::jsonb, 'Aqua, Cetearyl Alcohol, Hydrolysed Milk Protein, Argania Spinosa Oil, Shea Butter, Phenoxyethanol.', ARRAY['Damaged Hair','Chemically Treated'], 'Apply generously after shampooing, leave 10–15 minutes, rinse thoroughly. Use 1–2 times weekly.', 'haircare', ARRAY['Hair Care'], ARRAY['Hair Care Routine'], 475, 899, 35, 'HL-HRC-MSK-200', ARRAY[]::text[], '[]'::jsonb, false, false, 'live'),
(11, 'shower-gel', 'Shower Gel', 'Everyday gentle body wash', 'A gentle, sulphate-free body wash that cleanses without drying out skin, for daily use across the whole body.', ARRAY['Cleanses without over-drying','Light, non-lingering fragrance','Suitable for daily use'], '[{"name":"Glycerin","explanation":"Keeps the cleanse comfortable, not stripping."}]'::jsonb, 'Aqua, Sodium Cocoyl Isethionate, Glycerin, Cocamidopropyl Betaine, Citric Acid, Phenoxyethanol, Parfum.', ARRAY['All Skin Types'], 'Massage onto wet skin, lather, rinse thoroughly.', 'bodycare', ARRAY[]::text[], ARRAY[]::text[], 225, 399, 80, 'HL-BDC-SHG-300', ARRAY[]::text[], '[]'::jsonb, false, false, 'live')
on conflict (slug) do update set
  catalog_id = excluded.catalog_id,
  name = excluded.name,
  tagline = excluded.tagline,
  description = excluded.description,
  key_benefits = excluded.key_benefits,
  key_ingredients = excluded.key_ingredients,
  full_ingredient_list = excluded.full_ingredient_list,
  skin_hair_type = excluded.skin_hair_type,
  how_to_use = excluded.how_to_use,
  category = excluded.category,
  concern_tags = excluded.concern_tags,
  routine_tags = excluded.routine_tags,
  price_inr = excluded.price_inr,
  compare_at_price_inr = excluded.compare_at_price_inr,
  stock_quantity = excluded.stock_quantity,
  sku = excluded.sku,
  is_bestseller = excluded.is_bestseller,
  is_featured = excluded.is_featured,
  status = excluded.status,
  updated_at = now();
